on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install
      - name: "Package"
        run: yarn build
      - name: Upload vsix
        uses: actions/upload-artifact@v1
        with:
          name: vscode-drawio.vsix
          path: ./vscode-drawio.vsix
